language: node_js
node_js:
  - "7.9.0"
script: npm install -g pm2 && npm install && npm start && npm test
env:
  global: 
    - PROD=false
    - API_ADDRESS=localhost
    - API_PORT=1991
    - DB_USER=travis
    - DB_PASS=
    - DB_NAME=pokemarket
    - DB_DIALECT=mysql
    - DB_LOGGING=false
    - PAGARME_APIKEY=ak_test_WHgSu2XFmvoopAZMetV3LfA2RfEEQg
before_install:
  - mysql -e 'CREATE DATABASE pokemarket;'
